### ISSUE TITLE
File Open Error

### ISSUE THREAD

**Issue by ckreiling** [tonyrog/afunix#10]
Hi,

I'm trying to use your library from Elixir in order to connect to a Unix domain socket of type `SOCK_SEQPACKET`. I keep receiving the error: `{:error, {:open_error, -10}}`, which doesn't seem to include a Unix error code. Do you have any suggestions for how to approach this error?

**Comment by tonyrog** [comment]
afunix is using SOCK_STREAM and so does local_tcp in OTP. But it looks like you could write your own connect using inet:open end prim_inet:connect if you look in for example local_tcp:do_connect
setting type to seqpacket.
