### ISSUE TITLE
R19.0.5 getting error connecting

### ISSUE THREAD

**Issue by vans163** [tonyrog/afunix#6]
(client)10> afunix:connect("/tmp/socket", []).
** exception error: undefined function inet:translate_ip/1
     in function  inet:connect_options/2 (inet.erl, line 723)
     in call from afunix:do_connect/3 (/home/user/_build/default/lib/afunix/src/afunix.erl, line 230)

**Comment by tonyrog** [comment]
Thanks. No support for R19 yet. Sorry.

**Comment by vans163** [comment]
Np, so far having success with the unix_socket support that shipped with R19. Had a rough patch at first so looked for external libs because there was no documentation about how to use it.

**Comment by tonyrog** [comment]
I will do a fix afunix to work with the native R19 support, since I am using even R15 still.
I just need time to get around doing it.

**Comment by tonyrog** [comment]
Ok. I pushed a fix I think that might work for both R19 and older versions. Please try.
Thanks.

**Comment by vans163** [comment]
@tonyrog I meant R19 has native unix_socket support, but its not documented well. I ended up using the native unix_socket support in R19.

**Comment by tonyrog** [comment]
I know R19 has native support. But it lacks a couple of security features that I need. I am also a user of the afunix library so I needed to fix it anyway to be able to run my code on R19. So no worries ;-)
